---
title: ""
runningheader: "COMM 8021 Integrated Social Media" # only for pdf output
subtitle: "" # only for html output
author: "Martin Roberts"
date: "`r Sys.Date()`"
output:
  word_document:
  tufte::tufte_handout:
    citation_package: natbib
    latex_engine: xelatex
  tufte::tufte_book:
    citation_package: natbib
    latex_engine: xelatex
  tufte::tufte_html:
    tufte_variant: "envisioned"
link-citations: yes
---
## COMM 8021 INTEGRATED SOCIAL MEDIA

Fitchburg State University  
Communications Media Department  
MS in Applied Communication: Social Media Concentration  

Schedule: Monday 16 May – Monday 4 July 2022  
Instructor: Dr. Martin Roberts  
Contact: [Email](mailto:mrober40@fitchburgstate.edu)  

***  

## OVERVIEW 

This course provides students the opportunity to learn about advanced applications of social media and produce high quality content for organizations. Issues addressed include search engine optimization (SEO), workflow, convergence, production of culture, conscientious posting, and coordination between networked audiences and publics. The course examines communication theory and practices, how they are integrated into and illustrated in social media, and how this affects users and producers. Social media are ever-evolving tool-sets and distribution platforms, and they are linked by a core set of skills and best practices. The course applies these core skills and practices to user organizations as they relate to business and communicative contexts.

***

## OBJECTIVES

By the end of the course, students should have acquired the following skills:  

- Understand the intersection of social media practices with communication theory to determine their best uses in both practical and academic contexts    
- Examine how the world of social media works through research into historical communication practices  
- Propose effective communication strategies for local businesses based on theoretical evidence obtained through research  
- Create entry-level and intermediate social media strategies for outreach and content generation  
- Participate in group discussion to break down advanced readings and apply them to practical problems  
- Produce theory-based documentation in individual and group-based projects for social media  
- Speculate in an informed way about the future of social media and applied social media practices by drawing both on reading assignments and extracurricular activities as a basis for further understanding of social media affordances 

***

## READING ASSIGNMENTS

**Required Texts**  
Frick, T., & Eyler-Werve, K. (2015). _Return on engagement: Content strategy and web design techniques for digital marketing_. 2nd Edition. Taylor & Francis, New York.

Jenkins, H., Ford, S., & Green, J. (2013). _Spreadable media: Creating value and meaning in a networked culture_. New York University Press, New York.

**Other Sources**  
Jenkins, H., “Quentin Tarantino’s _Star Wars_? Grassroots Creativity Meets the Media Industry,” in _Convergence Culture_.  

Marwick, A. (2013). “Online Identity.” In Hartley, J. Burgess, J. & Bruns, A. (eds), _Companion to New Media Dynamics_. Blackwell Companions to Cultural Studies. Malden, MA: Blackwell, pp. 355-364.  

Peterson, R., & Anand, N. (2004). "The Production of Culture Perspective." _Annual Review of Sociology_. 30, 311-334.  

***

## COURSE INFORMATION

**Blackboard**  
We will be using the Blackboard Learning Management System (LMS) as the primary platform for the course. Please be sure to check in to the site at least once daily M-F to check the Announcements page and the Discussion forum for the week.

**Sources**  
Reading assignments will be either from Required texts, linked to online, or available as PDF documents.   

PDF documents and the syllabus will be available for download in the [Course Repository](https://github.com/mroberts1/integrated-social-media-summer-2022) hosted on GitHub: please bookmark this link. The <pdf> folder on the repo will have copies of all PDF chapters and articles, which may be downloaded either individually (click on the document in question and then the Download button) or collectively in the zip file.

***  

## READING SCHEDULE

**Week 1** Mon 05/16/22

- Marwick, “Online Identity”    
- Jenkins Ford, & Green, _Spreadable Media_, ch. 1: “Where Web 2.0 Went Wrong”   
- Frick & Eyler-Werve, _Return on Engagement_, ch. 1: “Digital Marketing Strategy Basics”  

***

**Week 2** Mon 05/23/22

- Frick & Eyler-Werve, _Return on Engagement_, ch. 2: “Content Strategy”  
- Jenkins, “Quentin Tarantino’s _Star Wars_? Grassroots Creativity Meets the Media Industry”   
- Peterson & Anand, “The Production of Culture Perspective”  

***

**Week 3** Mon 05/30/22

- Frick & Eyler-Werve, _Return on Engagement_, chs. 3-4: “SEO and Content Strategy”; “Design Strategy: An Integrated Approach” 
- Jenkins Ford, & Green, _Spreadable Media_, ch. 2: “Reappraising the Residual”

***

**Week 4** Mon 06/06/22

- Frick & Eyler-Werve, _Return on Engagement_, ch. 5: “Measurement Strategy”  
- Jenkins Ford, & Green, _Spreadable Media_, ch. 3: “The Value of Media Engagement”

***

**Week 5** Mon 06/13/22

- Frick & Eyler-Werve, _Return on Engagement_, ch. 6: “Writing for the Web”  
- Jenkins Ford, & Green, _Spreadable Media_, ch. 4: “What Constitutes Meaningful Participation?”

***

**Week 6** Mon 06/20/22

- Frick & Eyler-Werve, _Return on Engagement_, chs. 7-8: “Producing Web Video”;“Content and Social Networks”  
- Jenkins Ford, & Green, _Spreadable Media_, ch. 5: “Designing for Spreadability”  

***

**Week 7** Mon 06/27/22

- Jenkins Ford, & Green, _Spreadable Media_, ch. 6: “Courting Supporters for Independent Media” 
- Frick & Eyler-Werve, _Return on Engagement_, chs. 9-10: “Creating Usable Designs”; “Climate Ride’s Pedal Power”  

***

## ASSIGNMENTS

**Discussion Forums** (25%)  
When due: every Friday by the end of the day

You will craft discussion questions prompted by your understanding of the course materials, as well as leading us into a greater understanding and application of the work. Grading will be based on comprehension of the materials, successful and creative application of the work, and the quality of the questions and discussion generated by your work. Write at least one discussion question illustrating your knowledge of the material, and comment on your classmates’ materials too. Note: the best questions will summarize the readings at the beginning and then ask smart questions. This way you will make sure you are providing a cover of all applicable material for these writers.

**Content Framework: Goals & Plan** (20%)  
Using the content framework format described in chapter 1 of the _Return on Engagement textbook_ as a guide, develop a content strategy for an account or platform of your choice. Grading will be based on  utilization of readings and social media planning. Complete the assigned forms and discuss your plans with me during Week Two, with the final version due by the end of Week Three.

Part One: Due in Week Two  
Part Two (Write-up): Due in Week Three  

**Research Paper** (25%)  
Due in Week Five  

Required length: 1,000-1,500 words, excluding bibliography page in Chicago citation format (which should also be used for in-text citations).

Using the concept of convergence as described by Jenkins et al., describe a business that has successfully incorporated social media into their business plan. (NB: you may not use any of the actual businesses or organizations cited in Jenkins’s book; use more recent organizations.) Use at least 2-3 different sources from in-class readings and out-of-class materials to support your claims. What are the reasons that this business has survived in the ever-changing media environment? Describe the production of culture for this company or organization, and explain how it has translated into 21st-century values. You should also use other applicable theoretical lenses to explain how this business has moved forward. I will be happy to hold one-on-one conferences to discuss ideas for case studies.

**Final Project** (30%)  
Due Monday 4 July.

2,000–2,500 words, excluding references (Chicago citation style, in-text and separate reference page). Develop a strategy for integrating social media into your own work, either as an individual or for the company that you work for. This strategy should explicitly try to connect theory with  practice. What reading assignments support the decisions you make? What theoretical concepts are you bringing into your work as a result of the choices you make, and how will that affect your potential friends, followers, and customers in both the online and embodied world? What is the production of culture as you see it playing out in your choices? How have each of your assignments helped you reach this point where you are ready to apply a theoretical lens to a practical decision or set of decisions? What practical lessons are you using with the Frick & Eyler-Werve text? By explaining how your work reflects your knowledge, you are displaying your portfolio to an employer and making a practical connection between theory and application. This project is the culmination of all your knowledge in this area, so make sure it is truly representative of your final output.

***

## LATE POLICY

Assignments submitted late will lose 1/2 of a grade per day, beginning at the end of class and including weekends and holidays. This means that a paper, which would have received an A- if it was on time, will receive a B+ the next day, B- for two days late, and so on. Time management, preparation for our meetings, and timely submission of your work comprise a significant dimension of your professionalism. As such, your work must be completed by the beginning of class on the day it is due. If you have a serious problem that makes punctual submission impossible, please discuss this matter with me before the due date so that we can make alternative arrangements. Because you are given plenty of time to complete your work, and major due dates are given to you well in advance, last minute problems should not preclude handing in assignments on time.

***

## MANDATORY REPORTER
Fitchburg State University is committed to providing a safe learning environment for all students that is free of all forms of discrimination and harassment. Please be aware all FSU faculty members are “mandatory reporters,” which means that if you tell me about a situation involving sexual harassment, sexual assault, dating violence, domestic violence, or stalking, I am legally required to share that information with the Title IX Coordinator. If you or someone you know has been impacted by sexual harassment, sexual assault, dating or domestic violence, or stalking, FSU has staff members trained to support you. If you or someone you know has been impacted by sexual harassment, sexual assault, dating or domestic violence, or stalking, please visit [http://fitchburgstate.edu/titleix](http://fitchburgstate.edu/titleix) to access information about university support and resources.

***

## WELLNESS
[Health Services](http://www.google.com/url?q=http%3A%2F%2Fwww.fitchburgstate.edu%2Foffices-services-directory%2Fhealth-services%2F&sa=D&sntz=1&usg=AFQjCNEw5V0i0hL5DVO5b43gejNNaAt4ig)

Hours: Monday-Friday 8:30AM-5PM
Location: Ground Level of Russell Towers (across from the entrance of Holmes Dining Hall) Phone: (978) 665-3643/3894

[Counseling Services](http://www.google.com/url?q=http%3A%2F%2Fwww.fitchburgstate.edu%2Foffices-services-directory%2Fcounseling-services%2F&sa=D&sntz=1&usg=AFQjCNEYiS4EmSvWerpp2bKr5lTpouPuqQ)

The Counseling Services Office offers a range of services including individual, couples and group counseling, crisis intervention, psychoeducational programming, outreach ALTERNATIVE ECOSYSTEMSs, and community referrals. Counseling services are confidential and are offered at no charge to all enrolled students. Staff at Counseling Services are also available for consultation to faculty, staff and students. Counseling Services is located in the Hammond, 3rd Floor, Room 317.

[Fitchburg Anti-Violence Education (FAVE)](http://www.google.com/url?q=http%3A%2F%2Fwww.fitchburgstate.edu%2Foffices-services-directory%2Ffitchburg-anti-violence-education%2F&sa=D&sntz=1&usg=AFQjCNFi5qy-wunMxX-hoWbA9YwT8aa4Ig)

FAVE collaborates with a number of community partners (e.g., YWCA Domestic Violence Services, Pathways for Change) to meet our training needs and to link survivors with community based resources. This site also features [resources](http://www.google.com/url?q=http%3A%2F%2Fwww.fitchburgstate.edu%2Foffices-services-directory%2Ffitchburg-anti-violence-education%2Ffitchburg-anti-violence-education-resources%2F&sa=D&sntz=1&usg=AFQjCNF9KZ2O1AvPMLJTHdNg1DfmYYtgog) for help or information about dating violence, domestic violence, sexual assault and stalking. If you or someone you know is in an abusive relationship or has been a victim of sexual assault, there are many places to go for help. Many can be accessed 24 hours a day, seven days a week, 365 days a year. On campus, free and confidential support is provided at both Counseling Services and Health Services.

**Community Food Pantry**
Food insecurity is a growing issue and it certainly can affect student learning. The ability to have access to nutritious food is incredibly vital. The Falcon Bazaar, located in Hammond G 15, is stocked with food, basic necessities, and can provide meal swipes to support all Fitchburg State students experiencing food insecurity for a day or a semester.

The university continues to partner with Our Father's House to support student needs and access to food and services. All Fitchburg State University students are welcome at the Our Father’s House Community Food Pantry. This Pantry is located at the Faith Christian Church at 40 Boutelle St., Fitchburg, MA and is open from 5-7pm. Each “household” may shop for nutritious food once per month by presenting a valid FSU ID.

***

## ACADEMIC INTEGRITY
You are strongly encouraged to consult the University's [Academic Integrity Policy](http://www.fitchburgstate.edu/offices-services-directory/office-of-student-conduct-mediation-education/academic-integrity/). Students are expected to do their own work. Plagiarism and cheating are inexcusable. Any instance of plagiarism or cheating will automatically result in a zero on the assignment and may be reported the Office of Student and Academic Life at the discretion of the instructor.

Plagiarism includes, but is not limited to:

- Using papers or work from another class.
- Using another student's paper or work from any class.
- Copying work or a paper from the Internet.
- The egregious lack of citing sources or documenting research.
    
_If you're not clear on what is or is not plagiarism, ASK. The BEST case scenario if caught is a zero on that assignment, and ignorance of what does or does not count is not an excuse. That being said, I'm a strong proponent of the concept of [Fair Use](https://en.wikipedia.org/wiki/Fair_Use). Just attribute what you use--and, again, ASK if there's any doubt._

***

## AMERICANS WITH DISABILITIES ACT (ADA)
If you need course adaptations or accommodations because of a disability, if you have emergency medical information to share with the instructor, or if you need special arrangements in case the building must be evacuated, please inform the faculty member as soon as possible.

***

## TECHNOLOGY
At some point during the semester you will likely have a problem with technology. Your laptop will crash; your iPad battery will die; a recording you make will disappear; you will accidentally delete a file; the wireless will go down at a crucial time. These, however, are inevitabilities of life, not emergencies. Technology problems are not excuses for unfinished or late work. Bad things may happen, but you can protect yourself by doing the following:

- Plan ahead: A deadline is the last minute to turn in material. You can start—and finish—early, particularly if challenging resources are required, or you know it will be time consuming to finish this project.
- Save work early and often: Think how much work you do in 10 minutes.
- Make regular backups of files in a different location: Between Box, Google Drive, Dropbox, and iCloud, you have ample places to store and backup your materials. Use them.
- Save drafts: When editing, set aside the original and work with a copy.
- Practice safe computing: On your personal devices, install and use software to control viruses and malware.
    
  ***

## GRADING POLICY
Grading for the course will follow the FSU grading policy below:

A: 95-100  
A-: 92-94  
B+: 89-91  
B: 86-88  
B-: 83-85  
C+: 80-82  
C: 77-79  
C-: 74-76  
D+: 71-73  
0.0: < 70  

***

## ACADEMIC RESOURCES

[Writing Center](http://www.fitchburgstate.edu/offices-services-directory/tutor-center/writing-help/)

[Academic Policies](http://catalog.fitchburgstate.edu/content.php?catoid=13&navoid=851)

[Disability Services](http://www.fitchburgstate.edu/offices-services-directory/disability-services/)

[Fitchburg State Alert system for emergencies, snow closures/delays, and faculty absences](https://www.getrave.com/login/fitchburgstate/)

[University Career Services](http://www.fitchburgstate.edu/offices-services-directory/career-counseling-and-advising/career-services/)

***
